import "./globals.css";
import Header from "@/components/Header/Header";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "VibeLink",
  description: "Generated by Mr.Chetan Timsina",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
