import "./globals.css";
import Header from "@/components/Header/page";

export const metadata = {
  title: "VibeLink",
  description: "Generated by Mr.Chetan Timsina",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
